### ISSUE TITLE
Dell XPS 13 9315

### ISSUE THREAD

**Issue by AdamWill** [hughsie/fwupd-spi-dumps#10]
Had to use the script. Script output:

    [root@xps13a adamw]# python3 /tmp/dump-mtd-ifd.py 
    checking /dev/mtd0...
    reading from /dev/mtd0...
    descriptor_map0=0x40003
    descriptor_map1=0x46100208
    descriptor_map2=0x1401B0
    num_regions=0xA
    flash_region_base_addr=0x40
    flash_descriptor_reg0=0x0
    flash_descriptor_reg1=0x3FFF2000
    flash_descriptor_reg2=0xB9C0121
    flash_descriptor_reg3=0x7FFF
    flash_descriptor_reg4=0x7FFF
    flash_descriptor_reg5=0x7FFF
    flash_descriptor_reg6=0x7FFF
    flash_descriptor_reg7=0x7FFF
    flash_descriptor_reg8=0x1200001
    flash_descriptor_reg9=0x1FFF0B9D
    image_size=0x3ffffff
    reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
    reading... IfdPartition(region=bios, offset=0x2000000, size=0x1ffffff)
    reading... IfdPartition(region=me, offset=0x121000, size=0xa7bfff)
    reading... IfdPartition(region=ie, offset=0x1000, size=0x11ffff)
    failed to read: [Errno 5] Input/output error
    reading... IfdPartition(region=10gbe, offset=0xb9d000, size=0x1462fff)
    failed to read: [Errno 5] Input/output error
    writing dell_inc.-xps-0b14.bin...
    done!

**Comment by hughsie** [comment]
Looks great, thanks!

    /home/hughsie/Code/fwupd-test-roms/dell-xps13-9315.bin
    FuEfiFirmwareFile                   : 0 -> 1165
    FuEfiFirmwareFilesystem             : 0 -> 71
    FuEfiFirmwareSection                : 0 -> 3481
    FuEfiFirmwareVolume                 : 0 -> 72
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 4
    Lines                               : 0 -> 39146
