### ISSUE TITLE
Dell Precision 3630 tower

### ISSUE THREAD

**Issue by gwir** [hughsie/fwupd-spi-dumps#12]
Here's my contribution

**Comment by hughsie** [comment]
Looks great, thanks!

    ../../fwupd-test-roms/dell-precision3630Tower.bin
    FuEfiFirmwareFile          : 0 -> 137
    FuEfiFirmwareFilesystem    : 0 -> 6
    FuEfiFirmwareSection       : 0 -> 310
    FuEfiFirmwareVolume        : 0 -> 6
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 3716

**Comment by gwir** [comment]
done

**Comment by hughsie** [comment]
and with https://github.com/fwupd/fwupd/pull/6662:

    ../../fwupd-test-roms/dell-precision3630Tower.bin
    FuEfiFirmwareFile          : 137 -> 154
    FuEfiFirmwareFilesystem    : 6 -> 10
    FuEfiFirmwareSection       : 310 -> 333
    FuEfiFirmwareVolume        : 6 -> 10
    Lines                      : 3716 -> 4071
