### ISSUE TITLE
Framework 13in laptop (11th gen)

### ISSUE THREAD

**Issue by Peetz0r** [hughsie/fwupd-spi-dumps#13]
This is the 11th gen (tiger lake) Framework 13, slightly different from #5 
```
# python dump-mtd-ifd.py 
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1101A0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF1400
flash_descriptor_reg2=0x10000001
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x7FFF
flash_descriptor_reg9=0x13FF1001
image_size=0x1ffffff
reading... IfdPartition(region=0x0 (desc), offset=0x0, size=0xfff)
reading... IfdPartition(region=0x1 (bios), offset=0x1400000, size=0xbfffff)
reading... IfdPartition(region=0x2 (me), offset=0x1000, size=0xffffff)
reading... IfdPartition(region=0x9 (10gbe), offset=0x1001000, size=0x3fefff)
failed to read: [Errno 5] Input/output error
writing framework-franbmcp-laptop-franbmcp0a.bin...
done!
```

**Comment by hughsie** [comment]
Works great, thanks. It's a little on the low side, and I'll update this issue if there are parsing fixes.

    ../../fwupd-test-roms/framework-franbmcp-laptop-franbmcp0a.bin
    FuEfiFirmwareFile          : 0 -> 479
    FuEfiFirmwareFilesystem    : 0 -> 10
    FuEfiFirmwareSection       : 0 -> 1691
    FuEfiFirmwareVolume        : 0 -> 10
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 17937
