### ISSUE TITLE
Lenovo ThinkPad T490s

### ISSUE THREAD

**Issue by rafal06** [hughsie/fwupd-spi-dumps#14]
I hope it helps!

**Comment by hughsie** [comment]
That worked great, thanks!

    ../../fwupd-test-roms/lenovo-thinkpad-t490s.bin
    FuEfiFirmwareFile          : 0 -> 1368
    FuEfiFirmwareFilesystem    : 0 -> 30
    FuEfiFirmwareSection       : 0 -> 4643
    FuEfiFirmwareVolume        : 0 -> 31
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 49788
