### ISSUE TITLE
Dell Inspiron 16 5620

### ISSUE THREAD

**Issue by ARandomDave** [hughsie/fwupd-spi-dumps#15]
[sudo] password for dave: 
Sorry, try again.
[sudo] password for dave: 
Sorry, try again.
[sudo] password for dave: 
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1401B0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF0800
flash_descriptor_reg2=0x7450121
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x1200001
flash_descriptor_reg9=0x7FF0746
image_size=0x1ffffff
reading... IfdPartition(region=0x0 (desc), offset=0x0, size=0xfff)
reading... IfdPartition(region=0x1 (bios), offset=0x800000, size=0x17fffff)
reading... IfdPartition(region=0x2 (me), offset=0x121000, size=0x624fff)
reading... IfdPartition(region=0x8 (ie), offset=0x1000, size=0x11ffff)
failed to read: [Errno 5] Input/output error
reading... IfdPartition(region=0x9 (10gbe), offset=0x746000, size=0xb9fff)
failed to read: [Errno 5] Input/output error
writing dell_inc.-inspiron-inspiron_16_5620-0baa.bin...
done!

**Comment by hughsie** [comment]
Looks great, thanks!

    ../../fwupd-test-roms/dell-inspiron-inspiron_16_5620-0baa.bin
    FuEfiFirmwareFile          : 0 -> 1169
    FuEfiFirmwareFilesystem    : 0 -> 77
    FuEfiFirmwareSection       : 0 -> 3491
    FuEfiFirmwareVolume        : 0 -> 78
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 4
    Lines                      : 0 -> 39315
