### ISSUE TITLE
Acer Swift SF313-52

### ISSUE THREAD

**Issue by tstoeckler** [hughsie/fwupd-spi-dumps#16]
Hey there,

I hope I did everything correctly. The `sudo cat /dev/mtd0` did work but the python script did as well, so attaching the (zipped) bin that that one created, as well as the output:
```
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x4A100208
descriptor_map2=0x340B30
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0xFFF0600
flash_descriptor_reg2=0x5FF0001
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x7FFF
flash_descriptor_reg9=0x7FFF
image_size=0xffffff
reading... IfdPartition(region=0x0 (desc), offset=0x0, size=0xfff)
reading... IfdPartition(region=0x1 (bios), offset=0x600000, size=0x9fffff)
reading... IfdPartition(region=0x2 (me), offset=0x1000, size=0x5fefff)
writing acer-swift_3-swift_sf313-52-0000000000000000.bin...
done!
```

Let me know if you need anything else. And thanks for all your efforts, really awesome stuff!

**Comment by hughsie** [comment]
Useful, thanks. Less DXEs than I expected, and I'll debug a bit on Monday:

    ../../fwupd-test-roms/acer-swift_3-swift_sf313-52-0000000000000000.bin
    FuEfiFirmwareFile          : 0 -> 509
    FuEfiFirmwareFilesystem    : 0 -> 10
    FuEfiFirmwareSection       : 0 -> 1704
    FuEfiFirmwareVolume        : 0 -> 10
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 2
    Lines                      : 0 -> 18248
