### ISSUE TITLE
HP ZHAN 66 Pro 14 G5 Notebook PC

### ISSUE THREAD

**Issue by DarkmatterUAE** [hughsie/fwupd-spi-dumps#17]
HP ZHAN 66 Pro 14 G5 Notebook PC
https://support.hp.com/us-en/document/ish_6000404-6000449-16

Some system information and BIOS version information displayed in BIOS config page:

Product Name:
HP ZHAN 66 Pro 14 Inch G5 Notebook PC
Processor 1:
12th Gen Intel Core i5-1240P
System BIOS:
U73 Ver. 01.09.01 10/19/2023
SKU:
66Y03PC#AB2

BIOS Information
Current System BIOS Version:
U73 Ver. 01.09.01
Current BIOS Release Date:
10/19/23

Installation Data of Current BIOS:
01/09/24
Most Recent Update Check:
01/09/24

Note: I got an Input/Output error when dumping this file. dmesg:
```
root@localhost:/dev# pv mtd0 >/home/user/hp-zhan66-pro-14-inch-g5.bin
7.12MiB 0:00:04 [1.78MiB/s] [                <=>                                                                                                                                                                                             ]
pv: mtd0: read failed: Input/output error
7.75MiB 0:00:04 [1.80MiB/s] [                    <=>                                                                                                                                                                                         ]
root@localhost:/dev# dmesg
...unrelated...
[ 1692.579474] intel-spi 0000:00:1f.5: read error: 7c2000: 0x3f00e803
```

kernel version:
```
root@localhost:~# uname -a
Linux localhost 6.8.0-0.rc0.20240111gitde927f6c0b07.4.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jan 11 16:23:56 UTC 2024 x86_64 GNU/Linux
```

**Comment by DarkmatterUAE** [comment]
Using [dump-mtd-ifd.py](https://github.com/fwupd/fwupd/blob/wip/hughsie/ifd-helper/contrib/dump-mtd-ifd.py):
```
user@localhost:~/Downloads$ sudo python ./dump-mtd-ifd.py 
[sudo] password for user: 
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1401B0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF0C00
flash_descriptor_reg2=0x7C10001
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x7FFF
flash_descriptor_reg9=0xBFF07C2
image_size=0x1ffffff
reading... IfdPartition(region=0x0 (desc), offset=0x0, size=0xfff)
reading... IfdPartition(region=0x1 (bios), offset=0xc00000, size=0x13fffff)
reading... IfdPartition(region=0x2 (me), offset=0x1000, size=0x7c0fff)
reading... IfdPartition(region=0x9 (10gbe), offset=0x7c2000, size=0x43dfff)
failed to read: [Errno 5] Input/output error
writing hp-103c_5336an_hp_zbook-hp_zhan_66_pro_14_inch_g5_notebook_pc-66y03pc#ab2.bin...
done!
user@localhost:~/Downloads$ sudo dmesg |tail -n 20
[sudo] password for user: 
...unrelated...
[ 2074.003647] intel-spi 0000:00:1f.5: read error: 7c2000: 0x3f00e803
```

**Comment by hughsie** [comment]
fwupd didn't do a very good job of this one:

    FuEfiFirmwareVolume        : 0 -> 1
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 69

I'll debug this more on Monday -- many thanks for the contribution.

**Comment by hughsie** [comment]
> I'll debug this more on Monday

with https://github.com/fwupd/fwupd/pull/6672:

	../../fwupd-test-roms/hp_zhan_66_pro_14_inch_g5_notebook_pc-66y03pc#ab2.bin
	FuEfiFirmwareFile          : 0 -> 981
	FuEfiFirmwareFilesystem    : 0 -> 8
	FuEfiFirmwareSection       : 0 -> 3317
	FuEfiFirmwareVolume        : 1 -> 10
	Lines                      : 69 -> 35271
	WarningLines               : 0 -> 1

**Comment by DarkmatterUAE** [comment]
@hughsie Do you want me to test again?

**Comment by hughsie** [comment]
@DarkmatterUAE nope, no more action required on your part. Your image tripped an issue with the fwupd parser, and now it's fixed -- so your submission was 100% worthwhile and most appreciated.
