### ISSUE TITLE
Dell Inspiron 5491

### ISSUE THREAD

**Issue by e6c31d** [hughsie/fwupd-spi-dumps#19]

**Comment by hughsie** [comment]
Worked great, thanks:

    ../../fwupd-test-roms/dell-inspiron-5491.bin
    FuEfiFirmwareFile          : 0 -> 695
    FuEfiFirmwareFilesystem    : 0 -> 23
    FuEfiFirmwareSection       : 0 -> 2320
    FuEfiFirmwareVolume        : 0 -> 24
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 25101
