### ISSUE TITLE
Beelink MiniPC Intel Alderlake N95

### ISSUE THREAD

**Issue by mangelajo** [hughsie/fwupd-spi-dumps#24]
From: https://www.amazon.es/dp/B094VM2ZJM?psc=1&ref=ppx_yo2ov_dt_b_product_details

![image](https://github.com/hughsie/fwupd-spi-dumps/assets/1176434/20e3d85d-2a33-4318-9ef5-f378c68391fa)

**Comment by hughsie** [comment]
The parsing worked great on that, thanks!

    FuEfiFile                  : 0 -> 476
    FuEfiFilesystem            : 0 -> 20
    FuEfiSection               : 0 -> 1570
    FuEfiVolume                : 0 -> 20
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 17027
