### ISSUE TITLE
Lenovo Thinkpad X1 Carbon Gen 9

### ISSUE THREAD

**Issue by andreas-theo** [hughsie/fwupd-spi-dumps#26]
Attaching the compressed binary file.

**Comment by hughsie** [comment]
The parser liked that image, thanks!

    ../../fwupd-test-roms/lenovo-x1-carbon-gen9.bin
    FuEfiFile                  : 0 -> 732
    FuEfiFilesystem            : 0 -> 24
    FuEfiSection               : 0 -> 2468
    FuEfiVolume                : 0 -> 25
    FuIfdBios                  : 0 -> 1
    FuIfdFirmware              : 0 -> 1
    FuIfdImage                 : 0 -> 3
    Lines                      : 0 -> 26628
