### ISSUE TITLE
Dell Latitude 5320

### ISSUE THREAD

**Issue by marcosps** [hughsie/fwupd-spi-dumps#3]
Output of dump-mtd-idf.py --devname mtd1:

```
checking /dev/mtd1...
reading from /dev/mtd1...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1101A0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF1000
flash_descriptor_reg2=0xFFF0101
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x1000001
flash_descriptor_reg9=0x7FFF
image_size=0x1ffffff
reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
reading... IfdPartition(region=bios, offset=0x1000000, size=0xffffff)
reading... IfdPartition(region=me, offset=0x101000, size=0xefefff)
reading... IfdPartition(region=ie, offset=0x1000, size=0xfffff)
failed to read: [Errno 5] Input/output error
writing dell_inc.-latitude-0a1f.bin...
done!
```

Also, I had to pass --devname mtd1, as the default option (mtd0) returned an error:

```
checking /dev/mtd0...
Not Intel Corporation PCH SPI Controller, got 0000:00:1f.5
```

**Comment by hughsie** [comment]
Looks good! Can you attach the zip file please.

**Comment by marcosps** [comment]
I expected that you would like to address the EIO first, that's why I didn't attach it before :P

**Comment by hughsie** [comment]
Nah, the EIO is a hardware issue; we're trying to correlate the issues right now. Also the image looks great, thanks!

    FuEfiFirmwareFile                   : 0 -> 1082
    FuEfiFirmwareFilesystem             : 0 -> 54
    FuEfiFirmwareSection                : 0 -> 3354
    FuEfiFirmwareVolume                 : 0 -> 55
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 3
    Lines                               : 0 -> 37193
