### ISSUE TITLE
Dell XPS 8940 09c5

### ISSUE THREAD

**Issue by rynofinn** [hughsie/fwupd-spi-dumps#4]
SPI dump created like this:

# python dump-mtd-ifd.py 
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x5A100208
descriptor_map2=0x340E30
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF1000
flash_descriptor_reg2=0xFFF0101
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x1000001
flash_descriptor_reg9=0x7FFF
image_size=0x1ffffff
reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
reading... IfdPartition(region=bios, offset=0x1000000, size=0xffffff)
reading... IfdPartition(region=me, offset=0x101000, size=0xefefff)
reading... IfdPartition(region=ie, offset=0x1000, size=0xfffff)
failed to read: [Errno 5] Input/output error
writing dell_inc.-xps-09c5.bin...
done!

**Comment by rynofinn** [comment]
removed

**Comment by hughsie** [comment]
Thanks!

    ../libfwupdplugin/tests/ifd/dell-xps-09c5.bin
    FuEfiFirmwareFile                   : 0 -> 36
    FuEfiFirmwareFilesystem             : 0 -> 6
    FuEfiFirmwareSection                : 0 -> 77
    FuEfiFirmwareVolume                 : 0 -> 6
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 3
    Lines                               : 0 -> 1017

This one needs some parsing fixes -- so much appreciated.
