### ISSUE TITLE
Framework 13in laptop

### ISSUE THREAD

**Issue by rynofinn** [hughsie/fwupd-spi-dumps#5]
# python ./dump-mtd-ifd.py 
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1401B0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0x1FFF1000
flash_descriptor_reg2=0x8410081
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x800001
flash_descriptor_reg9=0xFFF0842
image_size=0x1ffffff
reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
reading... IfdPartition(region=bios, offset=0x1000000, size=0xffffff)
reading... IfdPartition(region=me, offset=0x81000, size=0x7c0fff)
reading... IfdPartition(region=ie, offset=0x1000, size=0x7ffff)
reading... IfdPartition(region=10gbe, offset=0x842000, size=0x7bdfff)
failed to read: [Errno 5] Input/output error
writing framework-13in_laptop-frandecp04.bin...
done!
[framework-13in_laptop-frandecp04.zip](https://github.com/hughsie/fwupd-spi-dumps/files/13895361/framework-13in_laptop-frandecp04.zip)

**Comment by hughsie** [comment]
Also needs work, thanks!

    /home/hughsie/Code/fwupd-test-roms/framework-13in_laptop-frandecp04.bin
    FuEfiFirmwareFile                   : 0 -> 177
    FuEfiFirmwareFilesystem             : 0 -> 8
    FuEfiFirmwareSection                : 0 -> 455
    FuEfiFirmwareVolume                 : 0 -> 8
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 4
    Lines                               : 0 -> 5347

**Comment by Peetz0r** [comment]
Note: this is the 12th gen (alder lake) variant
