### ISSUE TITLE
Lenovo ThinkPad E15

### ISSUE THREAD

**Issue by alcir** [hughsie/fwupd-spi-dumps#6]
`sudo ./dump-mtd-ifd.py`

**Comment by hughsie** [comment]
This needs lots of work in fwupd, so much appreciated for the dump!

    FuEfiFirmwareFile                   : 0 -> 9
    FuEfiFirmwareFilesystem             : 0 -> 3
    FuEfiFirmwareSection                : 0 -> 2
    FuEfiFirmwareVolume                 : 0 -> 4
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 3
    Lines                               : 0 -> 201

Could you also paste the console output of dump-mtd-ifd.py please? Thanks.

**Comment by alcir** [comment]
> Could you also paste the console output of dump-mtd-ifd.py please? Thanks.

Sure.

```
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x45100208
descriptor_map2=0x340330
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0xFFF0400
flash_descriptor_reg2=0x3FF003B
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x3A0001
flash_descriptor_reg9=0x7FFF
image_size=0xffffff
reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
reading... IfdPartition(region=bios, offset=0x400000, size=0xbfffff)
reading... IfdPartition(region=me, offset=0x3b000, size=0x3c4fff)
reading... IfdPartition(region=ie, offset=0x1000, size=0x39fff)
failed to read: [Errno 5] Input/output error
writing lenovo-thinkpad_e15-lenovo_mt_20re_bu_smb_fm_thinkpad_e15.bin...
done!
```

**Comment by hughsie** [comment]
Thanks!

**Comment by hughsie** [comment]
Okay, this is a bit better:

    FuEfiFirmwareFile                   : 9 -> 579
    FuEfiFirmwareFilesystem             : 3 -> 13
    FuEfiFirmwareSection                : 2 -> 2107
    FuEfiFirmwareVolume                 : 4 -> 14
    Lines                               : 201 -> 22232
