### ISSUE TITLE
Partaker mini PC

### ISSUE THREAD

**Issue by alcir** [hughsie/fwupd-spi-dumps#9]
Whether it would be useful 
Partaker
Model: H7-I3-1115G4-4

```
checking /dev/mtd0...
reading from /dev/mtd0...
descriptor_map0=0x40003
descriptor_map1=0x46100208
descriptor_map2=0x1101A0
num_regions=0xA
flash_region_base_addr=0x40
flash_descriptor_reg0=0x0
flash_descriptor_reg1=0xFFF0500
flash_descriptor_reg2=0x4FF0001
flash_descriptor_reg3=0x7FFF
flash_descriptor_reg4=0x7FFF
flash_descriptor_reg5=0x7FFF
flash_descriptor_reg6=0x7FFF
flash_descriptor_reg7=0x7FFF
flash_descriptor_reg8=0x7FFF
flash_descriptor_reg9=0x7FFF
image_size=0xffffff
reading... IfdPartition(region=desc, offset=0x0, size=0xfff)
reading... IfdPartition(region=bios, offset=0x500000, size=0xafffff)
reading... IfdPartition(region=me, offset=0x1000, size=0x4fefff)
writing default_string-default_string-default_string.bin...
done!
```

**Comment by hughsie** [comment]
Looks great, thanks!

    FuEfiFirmwareFile                   : 0 -> 517
    FuEfiFirmwareFilesystem             : 0 -> 17
    FuEfiFirmwareSection                : 0 -> 1702
    FuEfiFirmwareVolume                 : 0 -> 17
    FuIfdBios                           : 0 -> 1
    FuIfdFirmware                       : 0 -> 1
    FuIfdImage                          : 0 -> 2
    Lines                               : 0 -> 18386
